config/routes.rb
Rails.application.routes.draw do
    get 'follows/create'
    get 'follows/destroy'
    get 'likes/create'
    get 'likes/destroy'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :categories
    resources :post_categories
    resources :category_indexes
    resources :post_users
    resources :likes
    resources :follows, only: [:create, :destroy]
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    root 'posts#index'
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post, counter_cache: :likes_count
    belongs_to :user
    validates :post_id, presence: true
    validates :user_id, presence: true

    def create_good(user)
        likes.create(user_id: user.id)
    end

    def destroy_good(user)
        likes.find_by(user_id: user.id).destroy
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :set_current_user

    def create
        @post = Post.find(params[:post_id])
        @usre = User.find(params[:user_id])
        @like = Like.create(user_id: @current_user.id, post_id: params[:post_id])
        @likes = Like.where(post_id: params[:post_id])
        redirect_to controller: :posts, action: :index
    end

    def destroy
        like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
        like.destroy
        redirect_to controller: :posts, action: :index
    end

private

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>
<% if post.like_user(current_user.id) %>
  <%= button_to post_like_path(likes, post_id: post.id), method: :delete, id: "like-button", remote: true do %>
    <%= image_tag("icon_red_heart.png") %>
    <span>
      <%= post.likes_count %>
    </span>
  <% end %>
<% else %>
  <%= button_to post_likes_path(post), id: "like-button", remote: true do %>
    <%= image_tag("icon_heart.png") %>
    <span>
      <%= post.likes_count %>
    </span>
  <% end %>
<% end %>
<% end %>

app/views/likes/_like_user.html.erb
<% if logged_in? %>
<% if post.like_user(current_user.id) %>
    <%= image_tag("icon_red_heart.png") %>
    <span>
      <%= post.likes_count %>
    </span>
<% else %>
    <%= image_tag("icon_heart.png") %>
    <span>
      <%= post.likes_count %>
    </span>
<% end %>
<% end %>
</br>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");