config/routes.rb
Rails.application.routes.draw do
    get 'follows/create'
    get 'follows/destroy'
    get 'likes/create'
    get 'likes/destroy'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :categories
    resources :post_categories
    resources :category_indexes
    resources :post_users
    resources :likes
    resources :follows, only: [:create, :destroy]
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    has_many :posts
    has_many :likes, dependent: :destroy
    has_many :active_relationships,  class_name:  "Follow",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
    has_many :passive_relationships, class_name:  "Follow",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
    has_many :following, through: :active_relationships,  source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

    mount_uploader :picture, PictureUploader

    def follow(other_user)
        active_relationships.create(followed_id: other_user.id)
    end

    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    def following?(other_user)
        following.include?(other_user)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.find(params[:id])
        @post = Post.where(user_id: @user)
    end

    def show
        set_current_user
        @user = User.find(params[:id])
        @category = Category.find_by_category(params[:category])
        @all_post = Post.where(user_id: @user)

        if params[:category]
            @post = Post.category_with(params[:category]).where(user_id: @user)
        else
            @post = Post.where(user_id: @user)
        end

        @likes = Like.where(post_id: @all_post).count
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to controller: 'posts', action: 'index'
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end

    def following
        @title = "Following"
        @user  = User.find(params[:id])
        @users = @user.following
        render 'show_follow'
    end

    def followers
        @title = "Followers"
        @user  = User.find(params[:id])
        @users = @user.followers
        render 'show_follow'
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
    end

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_follow.html.erb
<%= form_for(@current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if @user != @current_user %>
  <div id="follow_form">
  <% if @current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>

<header>
    <p id="logo"><a href="">RailsCamp<span>Blog</span></a></p>
    <nav>
        <ul>
            <li>
                <a>
            <%=link_to 'トップ', posts_path %>
            <% if logged_in? %>
            <%= link_to 'カテゴリー', categories_path %>
            <%=link_to '新規投稿', new_post_path %>
            <%= link_to 'ユーザー', user_path(@current_user) %>
            <%=link_to 'ログアウト', logout_path, method: :delete %>
            <% else %>
            <%= link_to 'ユーザー登録', new_user_path %>
            <%=link_to 'ログイン', login_path %>
            <% end %>
            <div class="clear"></div>
                </a>
            </li>
        </ul>
    </nav>
    <div class="clear">
</div>
</header>

app/views/users/_index.html.erb
<% @users.each do |user| %>
<p class='picture_follower_index'>
    <%= image_tag user.picture.url if user.picture.present? %>
</p>
<%= link_to user.email, user_path(user) %>
<% end %>

app/views/users/_show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
 <td>  <%= user.email %> </td>
 <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
 <a href="<%= following_user_path(@user) %>">
   <strong id="following" class="stat">
     <%= @user.followings.count %>
   </strong>
   following
 </a>
 <a href="<%= followers_user_path(@user) %>">
   <strong id="followers" class="stat">
     <%= @user.followers.count %>
   </strong>
   followers
 </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(@current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div id="article_wrap">

        <div>
            <h2>
                <%= form_for @user do |f| %>
                <p>
                    <%= f.label :picture %></br>
                   <%= f.file_field :picture, id: :picture %>
                   <%= f.hidden_field :picture_cache %>
                   <% if  @user.errors.messages[:picture].any? %>
                   <span class="error"><%= @user.errors.messages[:picture][0] %></span>
                   <% end %>
                </p>
                <p class="picture">
                    Selected picture</br>
                    <%= image_tag @user.picture.url if @user.picture.present? %>
                </p>
                <p>
                    <%= f.label :email %></br>
                    <%= f.text_field :email %></br>
                    <%= f.label :password %></br>
                    <%= f.password_field :password %></br>
                    <%= f.label :password_confirmation, "Confirm Password" %></br>
                    <%= f.password_field :password_confirmation %></br>
                    <% if  @user.errors.messages[:email].any? %></br>
                   <span class="error"><%= @user.errors.messages[:email][0] %></span>
                   <% end %>
                </p>
            <p>
               <%= f.submit %>
            </p>
            <% end %>
        </h2>
        </div>

    </div>

    <div class="clear"></div>
    </div>

<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

app/views/users/index.html.erb
<div id="title">
    <div>
        <h2>
        <h1><%= @user.email %></h1>
        </h2>
    </div>
</div>

<% @post.each do |post| %>
<div id="article">
    <%= post.title %>
    <% end %>
</div>

<div id="article_wrap">

    <div id="content">
            <h2><p></p></h2>
    </div>


    <div id="sidebar">

        <h2>★PV数ランキング</h2>
        <ul>
        </ul>
    </div>
    <div class="clear"></div>
</div>

<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>

<header>
    <p id="logo"><a href="">RailsCamp<span>Blog</span></a></p>
    <nav>
        <ul>
            <li>
                <a>
            <%=link_to 'トップ', posts_path %>
            <% if logged_in? %>
            <%=link_to '新規投稿', new_post_path %>
            <%=link_to 'ログアウト', logout_path, method: :delete %>
            <% else %>
            <%= link_to 'ユーザー登録', new_user_path %>
            <%=link_to 'ログイン', login_path %>
            <% end %>
            <div class="clear"></div>
                </a>
            </li>
        </ul>
    </nav>
    <div class="clear">
    </div>
</header>

<div id="article_wrap">

        <div>
            <h2><% provide(:title, 'Sign up') %>
            <h1>Sign up</h1>

            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= form_for(@user) do |f| %>

                <p>
                    <%= f.label :picture %></br>
                   <%= f.file_field :picture, id: :picture %>
                   <%= f.hidden_field :picture_cache %>
                   <% if  @user.errors.messages[:picture].any? %>
                   <span class="error"><%= @user.errors.messages[:picture][0] %></span>
                   <% end %>
                </p>
                <p class="picture">
                    Selected picture</br>
                    <%= image_tag @user.picture.url if @user.picture.present? %>
                </p>

                  <%= f.label :email %>
                  </br>
                  <%= f.email_field :email %>
            </br>
                  <%= f.label :password %>
                  </br>
                  <%= f.password_field :password %>
            </br>
                  <%= f.label :password_confirmation, "Confirmation" %>
                  </br>
                  <%= f.password_field :password_confirmation %>
            </br>
                  <%= f.submit "Create my account", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div></h2>
        </div>

    <div class="clear"></div>
</div>

<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

app/views/users/show.html.erb
<%= render 'form' %>

<div id="user_article_wrap">
<div id="user_article_list">
    <h1>
        <% if params[:category] %>
            <%= "カテゴリー#{@category.category}　記事一覧"%>
        <% else %>
            記事一覧
        <% end %>
    </h1>
    <ul>
    <% @post.each do |post| %>
    <div>
    <p class="picture2">
        <%= image_tag post.picture.url if post.picture.present? %>
    </p>
     <h2><a><%= link_to post.title, post_path(post)%></a><h2>
    <p>
    <%= post.updated_at.strftime("%Y-%m-%d") %>

    <% post.post_categories.each do |f| %>
    <%= link_to f.category.category, user_path(category: f.category.category) %>
    <% end %>
    </p>

    <p>コメント<%= post.comments.count %></br></p>
    <%= render partial: 'likes/like_user', locals: { post: post, likes: @likes } %>

    <% if post.user == @current_user %>
    <%= link_to '編集', edit_post_path(post), class: 'command' %>
    <%= link_to '削除',
        post_path(post),
        method: :delete,
        class: 'command',
        data: { confirm: 'Sure?' }%>
        <% end %>
    </div>
    <% end %>
    </ul>
</div>

<div class="stats">
  <%= render 'shared/stats' %>
</div>

    <div id="user_sidebar">

        <h2>ユーザー設定</h2>
        <ul>
        <div class="user_profile">
            <p class='picture2'>
                <%= image_tag @user.picture.url if @user.picture.present? %>
            </p>
            <p>
                <%= @user.email %>
            </p>
        </div>
    </ul>

<%= render 'follow_form' if logged_in? %>

    <div class="good">
        もらったいいねの数
        <ul>
            <%= @likes %>
        </ul>
    </div>

    <% if @user == @current_user %>
    <div class="setting">
    <ul>
        <%= link_to 'メールアドレス変更', edit_user_path(@current_user) %>
    </ul>
</div>
    <% end %>
    </div>
    <div class="clear"></div>
</div>

<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    <p class='picture_follow_profile'>
      <%= image_tag @user.picture.url if @user.picture.present? %>
  </p>
      <h1><%= @user.email %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>posts:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
         <p class='picture_follower'>
            <%=image_tag user.picture.url if user.picture.present? %>
        </p>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render 'index' %>
      </ul>

    <% end %>
  </div>
</div>