config/routes.rb
Rails.application.routes.draw do
    get 'follows/create'
    get 'follows/destroy'
    get 'likes/create'
    get 'likes/destroy'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :categories
    resources :post_categories
    resources :category_indexes
    resources :post_users
    resources :likes
    resources :follows, only: [:create, :destroy]
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    root 'posts#index'
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
before_action :set_current_user

def create
    @user = User.find(params[:followed_id])
    @current_user.follow(@user)
    redirect_to @user
end

def destroy
    @user = Follow.find(params[:id]).followed
    @current_user.unfollow(@user)
    redirect_to @user
end

private

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<% if @post.user != @current_user %>
  <%= button_to user_follow_path(follows, follower_id: @post.user.followers), method: :delete, id: "like-button", remote: true do %>
    <%= image_tag("icon_red_heart.png") %>
    <span>
      <%= @post.user.followers_count %>
    </span>
  <% end %>
<% else %>
  <%= button_to user_follows_path(@post.user), id: "like-button", remote: true do %>
    <%= image_tag("icon_heart.png") %>
    <span>
      <%= @post.user.followers_count %>
    </span>
  <% end %>
<% end %>

app/views/follows/create.html.erb
<h1>Follows#create</h1>
<p>Find me in app/views/follows/create.html.erb</p>

app/views/follows/destroy.html.erb
<h1>Follows#destroy</h1>
<p>Find me in app/views/follows/destroy.html.erb</p>