config/routes.rb
Rails.application.routes.draw do
    get 'follows/create'
    get 'follows/destroy'
    get 'likes/create'
    get 'likes/destroy'
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :posts do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :categories
    resources :post_categories
    resources :category_indexes
    resources :post_users
    resources :likes
    resources :follows, only: [:create, :destroy]
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    root 'posts#index'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories, dependent: :destroy
    has_many :posts, :through => :post_categories, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

      # GET /authors
      # GET /authors.json
      def index
        @categories = Category.all
      end

      # GET /authors/1
      # GET /authors/1.json
      def show
      end

      # GET /authors/new
      def new
        @category = Category.new
      end

      # GET /authors/1/edit
      def edit
      end

      def create
          @category = Category.new(category_params)
          if @category.save
              redirect_to categories_path
          else
              render :edit
          end
      end

      # PATCH/PUT /authors/1.json
      def update
          if @category.update(category_params)
              redirect_to categories_path
          else
              render :edit
          end
      end

      def destroy
          @category.destroy
          redirect_to categories_path
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_category
            @category = Category.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def category_params
            params.require(:category).permit(:category)
        end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "#{category.category}の記事を見る", posts_path(category: category.category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Category', new_category_path %></br>
<%=link_to 'トップ', posts_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.category %>
  <%%>
</p>

<%= link_to '編集', edit_category_path(@category) %> |
<%= link_to '戻る', categories_path %>